[common]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_BT_NIMBLE_ROLE_CENTRAL_DISABLED
    -DCONFIG_BT_NIMBLE_ROLE_OBSERVER_DISABLED
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
lib_deps =
    knolleary/PubSubClient@^2.8
    h2zero/NimBLE-Arduino@^1.4

; USB upload (first flash or when physically connected)
[env:esp32dev]
extends = common
upload_speed = 921600

; OTA upload (wireless, after first flash)
[env:ota]
extends = common
upload_protocol = espota
upload_port = berbel-remote.local
upload_flags =
    --host_port=3232
